# Generated by Django 2.1.7 on 2019-04-02 21:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hello', max_length=300)),
                ('the_choices', multiselectfield.db.fields.MultiSelectField(choices=[('General_symptoms', 'General symptoms'), ('Head', 'Head'), ('Ear', 'Ear'), ('Eyes', 'Eyes'), ('Nose', 'Nose'), ('Legs', 'Legs')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalSymptoms', models.CharField(choices=[('asthenia', 'asthenia'), ('sweat', 'sweat'), ('fever', 'fever'), ('chills', 'chills'), ('malaise', 'malaise'), ('infection', 'infection'), ('fatigue', 'fatigue')], max_length=50)),
                ('headSymptoms', models.CharField(choices=[('dizziness', 'dizziness'), ('vertigo', 'vertigo'), ('fall', 'fall'), ('unresponsiveness', 'unresponsiveness'), ('weepiness', 'weepiness')], max_length=50)),
                ('earSymptoms', models.CharField(choices=[('hallucinations auditory', 'hallucinations auditory'), ('verbal auditory hallucinations', 'verbal auditory hallucinations'), ('hyperacusis', 'hyperacusis'), ('tinnitus', 'tinnitus')], max_length=50)),
                ('body_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomChecker.BodyPart')),
            ],
        ),
    ]
