# Generated by Django 2.1.7 on 2019-04-03 20:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsmodel',
            name='earSymptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hallucinations auditory', 'hallucinations auditory'), ('verbal auditory hallucinations', 'verbal auditory hallucinations'), ('hyperacusis', 'hyperacusis'), ('tinnitus', 'tinnitus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='symptomsmodel',
            name='generalSymptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('asthenia', 'asthenia'), ('sweat', 'sweat'), ('fever', 'fever'), ('chills', 'chills'), ('malaise', 'malaise'), ('infection', 'infection'), ('fatigue', 'fatigue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='symptomsmodel',
            name='headSymptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dizziness', 'dizziness'), ('vertigo', 'vertigo'), ('fall', 'fall'), ('unresponsiveness', 'unresponsiveness'), ('weepiness', 'weepiness')], max_length=50),
        ),
    ]
