# Generated by Django 2.1.7 on 2019-04-05 20:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0003_auto_20190405_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalSymptoms', multiselectfield.db.fields.MultiSelectField(choices=[('asthenia', 'asthenia'), ('sweat', 'sweat'), ('fever', 'fever'), ('chills', 'chills'), ('malaise', 'malaise'), ('infection', 'infection'), ('fatigue', 'fatigue')], default='fever', max_length=50)),
                ('headSymptoms', multiselectfield.db.fields.MultiSelectField(choices=[('dizziness', 'dizziness'), ('vertigo', 'vertigo'), ('fall', 'fall'), ('unresponsiveness', 'unresponsiveness'), ('weepiness', 'weepiness')], default='fall', max_length=50)),
                ('earSymptoms', multiselectfield.db.fields.MultiSelectField(choices=[('hallucinations auditory', 'hallucinations auditory'), ('verbal auditory hallucinations', 'verbal auditory hallucinations'), ('hyperacusis', 'hyperacusis'), ('tinnitus', 'tinnitus')], default='tinnitus', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='earSymptoms',
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='generalSymptoms',
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='headSymptoms',
        ),
        migrations.AddField(
            model_name='symptom',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomChecker.BodyPart'),
        ),
    ]
