# Generated by Django 2.1.7 on 2019-04-12 18:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0005_auto_20190406_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='generalSymptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('asthenia', 'asthenia'), ('sweat', 'sweat'), ('fever', 'fever'), ('chills', 'chills'), ('malaise', 'malaise'), ('infection', 'infection'), ('fatigue', 'fatigue')], max_length=50),
        ),
    ]
