# Generated by Django 2.1.7 on 2019-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0006_auto_20190413_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='earSymptoms',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='generalSymptoms',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='headSymptoms',
        ),
        migrations.AddField(
            model_name='symptom',
            name='enterSymptoms',
            field=models.TextField(default='Enter Your symptoms separated by ;', max_length=1000),
        ),
    ]
