# Generated by Django 2.1.7 on 2019-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0007_auto_20190414_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('genericName', models.CharField(max_length=50)),
                ('genericPrice', models.IntegerField(max_length=100)),
            ],
        ),
    ]
