# Generated by Django 2.1.7 on 2019-04-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0008_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='genericPrice',
        ),
    ]
