# Generated by Django 2.1.7 on 2019-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptomChecker', '0009_remove_search_genericprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='genericPrice',
            field=models.IntegerField(default=0),
        ),
    ]
